/* UI TYPES */
export const SET_LOCATION = 'SET_LOCATION'
export const SET_ALERT = 'SET_ALERT'
export const TOGGLE_MODAL = 'TOGGLE_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'
export const TOGGLE_CONFIRM_ALERT = 'TOGGLE_CONFIRM_ALERT'
/* SOCKET TYPES */
export const SET_PING = 'SET_PING'
export const SET_CONNECTION = 'SET_CONNECTION'
export const SET_CLIENT = 'SET_CLIENT'
export const SET_READY = 'SET_READY'
export const SET_START_PING = 'SET_START_PING'

export const SET_COMMITSET_LIST = 'SET_COMMITSET_LIST'
export const SET_COMMITSET = 'SET_COMMITSET'
export const SET_COMMITS_LIST = 'SET_COMMITS_LIST'
export const SET_COMMIT = 'SET_COMMIT'
export const SET_BUILD_COMMIT = 'SET_BUILD_COMMIT'